import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

type Props = {
  title?: string;
  children: React.ReactNode;
};

const Container = ({ title = "Inventario", children }: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex-1">{children}</main>
      <Footer />
    </>
  );
};

export default Container;
